# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    auth_token_user_provider:
        class: Test\ApiBundle\Security\TokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public:    false

    auth_token_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["TestApiBundle:Token"]

    user_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["TestApiBundle:User"]

    auth_token_authenticator:
        class:     Test\ApiBundle\Security\TokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false